### ISSUE TITLE
Provide "fast lane" for single-owner/user installers

### ISSUE THREAD

**Issue by aaaaalbert** [SensibilityTestbed/custominstallerbuilder#2]
We have a very common use case for Sensibility hackathons where participants configure custom installers for themselves only, to be used exclusively on their devices. Under these circumstances, creating a user, assigning it to one VM, downloading the two crypto user keys, and only then getting the actual download link for the Android device is too convoluted a process.

Instead, let's have a landing page that has all of the required things at once, with no config required. E.g., point users to https://sensibilityclearinghouse.poly.edu/custominstallerbuilder/fastlane, and they get redirected automatically to individual download pages that have their unique user key pairs and installers available right away.

**Comment by lukpueh** [comment]
I am on it! 

Also, what about taking it a step further and providing a pre-packaged [Demokit](https://sensibilityclearinghouse.poly.edu/demokit/sensibility-testbed-demokit.zip) that contains the according key pair?

**Comment by aaaaalbert** [comment]
That could become a security issue (you mustn't cache that tarball as it includes a private key), and increases complexity (as you'd have to handle user sessions so that only the creator can download that tarball). I'm not convinced.

**Comment by lukpueh** [comment]
@aaaaalbert My [proposed implementation](https://github.com/SeattleTestbed/custominstallerbuilder/pull/17) makes use of the session anyway (in order to re-use the existing facilities).

I don't see a security issue if we bundle the `Demokit` files (from disk) together with the `key pair` (from memory) and stream the archive to the client.

**Comment by aaaaalbert** [comment]
Re Fastlane: Thanks for your implementation! (It also proves that session management is not an issue indeed.)

Re bundling keys with demokit, this is subject of SeattleTestbed/custominstallerbuilder#2 and should be discussed there.

**Comment by aaaaalbert** [comment]
Fixed via PR SeattleTestbed/custominstallerbuilder#17.
